services:
  open_notebook:
    build:
      context: ..
      dockerfile: Dockerfile.single
    ports:
      - "8502:8502"
      - "5055:5055"
    env_file:
      - ./docker.env
    volumes:
      - ./notebook_data:/app/data
      - ./surreal_single_data:/mydata
    restart: always
